export const skills = [{"KS120P86XDXZJT3B7KVJ": {"skill_name": "(American Society For Quality) ASQ Certified", "skill_type": "Certification", "skill_len": 2, "high_surfce_forms": {"full": "asq certify"}, "low_surface_forms": ["asq certifi", "certifi asq", "asq"], "match_on_tokens": false}, "KS126XS6CQCFGC3NG79X": {"skill_name": ".NET Assemblies", "skill_type": "Hard Skill", "skill_len": 2, "high_surfce_forms": {"full": "net assembly"}, "low_surface_forms": ["net assembl", "assembl net"], "match_on_tokens": false}, "KS1200B62W5ZF38RJ7TD": {"skill_name": ".NET Framework", "skill_type": "Hard Skill", "skill_len": 2, "high_surfce_forms": {"full": "net framework"}, "low_surface_forms": ["net framework", "framework net"], "match_on_tokens": false}, "KS126XW78QJCF4TRV2X7": {"skill_name": ".NET Framework 1", "skill_type": "Hard Skill", "skill_len": 3, "high_surfce_forms": {"full": "net framework 1"}, "low_surface_forms": [], "match_on_tokens": true}, "KS126XY68BNKXSBSLPYS": {"skill_name": ".NET Framework 3", "skill_type": "Hard Skill", "skill_len": 3, "high_surfce_forms": {"full": "net framework 3"}, "low_surface_forms": [], "match_on_tokens": true}, "KS126XR63RKYVCKYDNBN": {"skill_name": ".NET Framework 4", "skill_type": "Hard Skill", "skill_len": 3, "high_surfce_forms": {"full": "net framework 4"}, "low_surface_forms": [], "match_on_tokens": true}, "KS126Y166NXP5X1SLV6V": {"skill_name": ".NET Reflector", "skill_type": "Hard Skill", "skill_len": 2, "high_surfce_forms": {"full": "net reflector"}, "low_surface_forms": ["net reflector", "reflector net"], "match_on_tokens": false}, "KS126Y16DLZ0N5THPLDM": {"skill_name": ".NET Remoting", "skill_type": "Hard Skill", "skill_len": 2, "high_surfce_forms": {"full": "net remoting"}, "low_surface_forms": ["net remot", "remot net"], "match_on_tokens": false}, "KSLGDAXJ4EFDMIOPMGL2": {"skill_name": ".nettiers", "skill_type": "Hard Skill", "skill_len": 1, "high_surfce_forms": {"full": "nettiers"}, "low_surface_forms": ["nettier"], "match_on_tokens": false}, "KS1200M68TBM4SXLZV0G": {"skill_name": "10 Gigabit Ethernet", "skill_type": "Hard Skill", "skill_len": 3, "high_surfce_forms": {"full": "10 gigabit ethernet"}, "low_surface_forms": [], "match_on_tokens": true}, "KSJCP2DYKDSINHFDMF51": {"skill_name": "1010data", "skill_type": "Hard Skill", "skill_len": 1, "high_surfce_forms": {"full": "1010data"}, "low_surface_forms": [], "match_on_tokens": false}, "KS1200L6T0NXQPW7Z8YR": {"skill_name": "10BASE-F (Physical Layer Protocols)", "skill_type": "Hard Skill", "skill_len": 2, "high_surfce_forms": {"full": "10base f"}, "low_surface_forms": ["10base f", "f 10base"], "match_on_tokens": false}}]

export const departments = ["HR", "IT", "Finance", "Marketing", "Software Engineering"]
export const experience = ["None", "6 months", "1 year", "2 years", "3 years", "4 years", "5 years", "6 years", "7 years", "8 years", "9 years", "10 years", "10+ years"]
export const qualification = ["BS-Computer Science", "BS-Social Sciences", "Bachelors of Business Administration"]
export const universities = ["Institute of Business Administration, Karachi", "Institute of Business Management, Karachi", "Lahore University of Management Sciences"]
export const unis = {
    "GCU": "Government College University",
    "KU": "Karachi University",
    "AIOU": "Allama Iqbal Open University",
    "BU": "Bahria University",
    "BUITEMS": "Balochistan University of Information Technology Engineering and Management Sciences",
    "BZU": "Bahauddin Zakariya University",
    "FUU": "Federal Urdu University",
    "GCUF": "Government College University Faisalabad",
    "HU": "Hazara University",
    "IU": "Indus University",
    "IU": "Iqra University",
    "IUB": "Islamia University of Bahawalpur",
    "LCWU": "Lahore College for Women University",
    "LUMS": "Lahore University of Management Sciences",
    "MAJU": "Mohammad Ali Jinnah University",
    "MUET": "Mehran University of Engineering and Technology",
    "PU": "Preston University",
    "FAST": "Foundation for Advancement of Science and Technology",
    "NUML": "National University of Modern Languages",
    "NUST": "National University of Sciences and Technology",
    "PUCIT": "Punjab University College of Information Technology",
    "QAU": "Quaid-e-Azam University",
    "RIU": "Riphah International University",
    "SALU": "Shah Abdul Latif University",
    "SVSU": "Swami Vivekanand Subharti University",
    "UCET": "University College of Engineering and Technology",
    "UCP": "University of Central Punjab",
    "UK": "University of Karachi",
    "UOB": "University Of Balochistan",
    "UP": "University of Peshawar",
    "UW": "University of Wah",
    "VUP": "Virtual University of Pakistan",
    "AAUR": "Arid Agriculture University, Rawalpindi",
    "AC": "Access Coordinator",
    "AC": "Apex Committee",
    "ADCP": "Advance Diploma in Clinical Psychology",
    "ADE": "Associate Degree in Education",
    "AERC": "Applied Economics Research Center",
    "AIDM": "Altamash Institute of Dental Medicine",
    "AIE": "Ali Institute of Education",
    "AIFD": "Asian Institute of Fashion Design",
    "AIMS": "American Institute of Management Sciences",
    "AIOU": "ALAMA IQBAL OPEN UNIVERSITY",
    "AIU": "Al-Hamd Islamic University",
    "AJKU": "Azad Jammu and Kashmir University",
    "AKU": "Aga Khan University",
    "AKUH": "Aga Khan University Hospital",
    "AL": "Assistant Librarian",
    "AMC": "Ayub Medical College",
    "AMDIP": "Association of Management Development Institutions in Pakistan",
    "APCOMS": "Army Public College of Management and Science",
    "APMSO": "All Pakistan Muttahida Students Organization",
    "ASAB": "Atta-ur-Rahman School of Applied Biosciences",
    "ASML": "Aisha Steel Mills Limited",
    "ASSMS": "Abdus Salam School of Mathematical Sciences",
    "AUP": "Agricultural University Peshawar",
    "AUR": "Asian University Rankings",
    "BASR": "Board of Advanced Studies and Research",
    "BBSU": "Benazir Bhutto Shaheed University",
    "BBSUL": "Benazir Bhutto Shaheed University Lyari",
    "BCA": "Bachelor of Computer Arts",
    "BCS": "Bachelor in Computer Science",
    "BDS": "Blood Donors Society",
    "BIIT": "Barani Institute of Information Technology",
    "BIMCS": "Bahria Institute of Management and Computer Science",
    "BKU": "Bacha Khan University",
    "BNU": "Beaconhouse National University",
    "BUET": "Balochistan University of Engineering and Technology",
    "BUITEMS": "Balochistan University of Information Technology, Engineering & Management Sciences",
    "BUITMS": "Balochistan University of Information Technology and Management Sciences",
    "BUMUN": "Bahria University Model United Nations",
    "BZU": "Bahauddin Zakaria University",
    "CAE": "College of Aeronautical Engineering",
    "CAMP": "Center for Advanced Mathematics and Physics",
    "CAMS": "College of Accounting and Management Sciences",
    "CASE": "Centre for Advanced Studies in Engineering",
    "CASPR": "Controls and Signal Processing Research",
    "CBM": "College of Business Management",
    "CDPM": "Centre for Disaster Preparedness and Management",
    "CEME": "College of Electrical and Mechanical Engineering",
    "CESET": "Centre for Emerging Sciences, Engineering and Technology",
    "CIIT": "COMSATS Institute of Information Technology",
    "CIMR": "Center for Integrated Mountain Research",
    "CIPS": "Centre for International Peace and Stability",
    "CMER": "Center for Management and Economic Research",
    "CUSIT": "City University of Science and Information Technology",
    "CUST": "Comsats University of Science and Technology",
    "DAE": "Diploma in Associate Engineering",
    "DAI": "Degree Awarding Institute",
    "DCET": "Dawood College of Engineering & Technology",
    "DIK": "Dera Ismail Khan",
    "DIT": "Diploma Information Technology",
    "DMC": "Detailed Marks Certificate",
    "DSS": "Defence & Strategic Studies",
    "DUCSU": "Dhaka University Central Student Union",
    "DUET": "Dawood University of Engineering and Technology",
    "ECAT": "Engineering College Admission Test",
    "ERN": "Education Resources Network",
    "ETC": "Education Testing Council",
    "FAST": "Foundation for the Advancement of Science and Technology",
    "FCCU": "Forman Christian College University",
    "FCS": "Faculty of Contemporary Studies",
    "FFCL": "Fauji Fertilizer Company Limited",
    "FFIMCS": "Fauji Foundation Institute of Management and Computer Sciences",
    "FIRST": "Faisalabad Institute of Research Science and Technology",
    "FJWU": "Fatima Jinnah Women University",
    "FMC": "Frontier Medical College",
    "FSCRD": "Federal Seed Certification and Registration Department",
    "FUCLAS": "Foundation University College of Liberal Arts and Sciences",
    "FUI": "Foundation University Islamabad",
    "FUIEMS": "Foundation University Institute of Engineering and Management Sciences",
    "FUMC": "Foundation University Medical College",
    "FUUAST": "Federal Urdu University of Arts Science and Technology",
    "GAT": "General Admission Test",
    "GAT": "General Assessment Test",
    "GAT": "Graduate Admission Test",
    "GCUF": "Government College University, Faisalabad",
    "GCWUF": "Government College Women University Faisalabad",
    "GCWUS": "Government College Women University Sialkot",
    "GSCWU": "Government Sadiq College Women University",
    "GU": "Gomal University",
    "GU": "Greenwich University",
    "H.E.C.": "Higher Education Commission",
    "HEC": "Higher Education Commision",
    "HF": "Hashoo Foundation",
    "HIIT": "Hamdard Institute of Information Technology",
    "HIMS": "Hamdard Institute of Management Sciences",
    "HITEC": "Heavy Industries Taxila Education City",
    "HITEWT": "Heavy Industries Taxila Education Welfare Trust",
    "HU": "Habib University",
    "HU": "Hajvery University",
    "HU": "Hamdard University",
    "IoBM": "Institute of Business & Management",
    "IBA": "Institue of Business Administration",
    "IBIT": "Institute of Business & Information Technology",
    "IBM": "Institute of Business and Management",
    "IBT": "Institute of Business & Technology",
    "ICP": "Islamia College Peshawar",
    "ICU": "Islamia College University",
    "IEMS": "Institute of E-Learning & Modern Studies",
    "IER": "Institute of Education and Research",
    "IGIS": "Institute of Geographical Information Systems",
    "IGT&E": "Inspector General of Training and Evaluation",
    "IIEC": "Islamic International Engineering College",
    "IIHE": "Indus Institute of Higher Education",
    "IIMC": "Islamic International Medical College",
    "IIU": "Islamic International University",
    "IIUI": "International Islamic University Islamabad",
    "IJT": "Islami Jamiat Talaba",
    "IMCG": "Islamabad Model College for Girls",
    "IMS": "Institute of Management Science",
    "INU": "Iqra National University",
    "IOT": "Indigenous On-Campus Training",
    "IPD": "Institute of Peace and Diplomatic",
    "IPP": "Institute of Public Policy",
    "IRD": "Institute for Research and Dialogue",
    "ISO": "Imamia Students Organization",
    "ISP": "Institute of Southern Punjab",
    "ISPA": "Institute of Space and Planetary Astrophysics",
    "ISSRA": "Institute for Strategic Studies Research and Analysis",
    "ITA": "Idara-e-Taleem-o-Agahi",
    "ITHM": "Institute of Tourism and Hotel Management",
    "ITU": "Information Technology University",
    "IU": "Isra University",
    "IUB": "Islamia University Bahawalpur"
  }

  export const quals = {
    "LLB": "Bachelor of Laws",
    "MA": "Master of Arts",
    "EE": "External Examiner",
    "BBA": "Bachelor of Business Administration",
    "BSc": "Bachelor of Science",
    "BSCS": "Bachelor of Science in Computer Science",
    "BCom": "Bachelor of Commerce",
    "BD": "Bachelor of Divinity",
    "NQF": "National Qualification Framework",
    "QN": "Quality Nominee",
    "TQT": "Total Qualification Time",
    "ACTP": "Adobe Certified Training Provider",
    "BArch": "Bachelor of Architecture",
    "BBS": "Bachelor of Business Studies",
    "BCL": "Bachelor of Civil Law",
    "BEd": "Bachelor of Education",
    "BEng": "Bachelor of Engineering",
    "BMin": "Bachelor of Ministry",
    "BPharm": "Bachelor of Pharmacy",
    "BSc": "Bachelor of Science in Economics",
    "BTech": "Bachelor of Technology",
    "CA": "Chartered Accountant",
    "DUniv": "Doctor of the University",
    "FHEQ": "Framework for Higher Education Qualifications",
    "FRGS": "Fellow of the Royal Geographical Society",
    "LSV": "Lead Standards Verifier",
    "ME": "Master of Engineering",
    "MIMMM": "Member of the Institute of Institute of Materials, Minerals and Mining",
    "RHCE": "Red Hat Certified Engineer",
    "RHCT": "Red Hat Certified Technician",
    "ACE": "Adobe Certified Expert",
    "ACS": "Assignment Checking Service",
    "AMCT": "Associate Member of the Association of Corporate Treasurers",
    "AMR": "Academic Management Review",
    "APM": "Academic Management Review",
    "APMR": "Annual Programme Monitoring Report",
    "B.C.A.": "Bachelor of Computer Applications",
    "BA": "Bachelor of Arts in Education",
    "BAcc": "Bachelor of Accounting",
    "BAdmin": "Bachelor of Administration",
    "BAgr": "Bachelor of Agriculture",
    "BASc": "Bachelor of Arts and Science",
    "BCA": "Bachelor of Commerce and Administration",
    "BDes": "Bachelor of Design",
    "BDiv": "Bachelor of Divinity",
    "BE": "Bachelor of Engineering",
    "BEcon": "Bachelor of Economics",
    "BFA": "Bachelor of Fine Arts",
    "BFin": "Bachelor of Finance",
    "BHSc": "Bachelor of Health Science",
    "BL": "Bachelor of Law",
    "BLib": "Bachelor of Librarianship",
    "BLitt": "Bachelor of Letters",
    "BLS": "Bachelor of Library Studies",
    "BM": "Bachelor of Medicine",
    "BMet": "Bachelor of Metallurgy",
    "BMid": "Bachelor of Midwifery",
    "BMSc": "Bachelor of Medical Science",
    "BMus": "Bachelor of Music",
    "BMusEd": "Bachelor of Music Education",
    "BN": "Bachelor of Nursing",
    "BPhil": "Bachelor of Philosophy",
    "BPhys": "Bachelor of Physics",
    "Bs": "Bachelor of Surgery",
    "BScAgr": "Bachelor of Science in Agriculture",
    "BScFor": "Bachelor of Science in Forestry",
    "BSN": "Bachelor of Science in Nursing",
    "BSocSc": "Bachelor of Social Science",
    "BSS": "Bachelor of Social Studies",
    "BSW": "Bachelor of Social Work",
    "BTh": "Bachelor of Theology",
    "BTheol": "Bachelor of Theology",
    "CCA": "Citrix Certified Administrator",
    "CCEA": "Citrix Certified Enterprise Administrator",
    "CCEA": "Council for the Curriculum, Examinations and Assessment",
    "CCIE": "Cisco Certified Internetwork Expert",
    "CCM": "Certified Case Manager",
    "CCNA": "Cisco Certified Network Associate",
    "CCNP": "Cisco Certified Network Professional",
    "CDM": "Curriculum Development Manager",
    "CNA": "Certified Nursing Assistant",
    "CNM": "Certified Nurse Midwife",
    "CNS": "Clinical Nurse Specialist",
    "COTA": "Certified Occupational Therapy Assistant",
    "CPD": "Continued Professional Development",
    "CPL": "Certified Professional Logistician",
    "CQM": "Centre Quality Manager",
    "CRTT": "Certified Respiratory Therapy Technician",
    "DCH": "Doctor of Surgery",
    "DDS": "Doctor of Dental Surgery",
    "DLitt": "Doctor of Letters",
    "DSc": "Doctor of Science",
    "DTech": "Doctor of Technology",
    "DVM": "Doctor of Veterinary Medicine",
    "EMT": "Emergency Medical Technician",
    "EngD": "Doctor of Engineering",
    "EOL": "Edexcel Online",
    "FE": "Further Education",
    "GLH": "Guided Learning Hours",
    "IV": "Internal Verifier",
    "JCQ": "Joint Council for Qualifications",
    "LIV": "Lead Internal Verifier",
    "LPN": "Licensed Practical Nurse",
    "LVN": "Licensed Vocational Nurse",
    "M.Arch.": "Master of Architecture",
    "MBA": "Master of Business Administration",
    "MCAD": "Microsoft Certified Application Developer",
    "MCDST": "Microsoft Certified Desktop Support Technician",
    "MCPD": "Microsoft Certified Professional Developer",
    "MCSA": "Microsoft Certified Systems Administrator",
    "MCSE": "Microsoft Certified Systems Engineer",
    "MCT": "Microsoft Certified Trainer",
    "MCTS": "Microsoft Certified Technology Specialist",
    "ME": "Medical Examiner",
    "MEng": "Master of Engineering",
    "MICS": "Member of the Institute of Chartered Shipbrokers",
    "MMath": "Master of Mathematics",
    "MOS": "Microsoft Office Specialist",
    "MOUS": "Microsoft Office User Specialist",
    "MPH": "Master of Public Health",
    "MPhil": "Master of Philosophy",
    "MPhys": "Master of Physics",
    "MRAeS": "Member of the Royal Aeronautical Society",
    "MRINA": "Member of the Royal Institute of Naval Architects",
    "MRL": "Medical Records Librarian",
    "MS": "Master of Science",
    "MSD": "Master of Science in Dentistry",
    "MSt": "Master of Studies",
    "MusB": "Bachelor of Music",
    "NP": "Nurse Practitioner",
    "OFQUAL": "Office of Qualifications and Examinations Regulation",
    "OIA": "Office of the Independent Adjudicator",
    "OT": "Occupational Therapist",
    "PA": "Physician Assistant",
    "PhD": "Doctor of Philosophy",
    "PSM": "Principal Standards Manager",
    "PT": "Physical Therapist",
    "PTA": "Physical Therapist Assistant",
    "QAA": "The Quality Assurance Agency for Higher Education",
    "QCF": "Qualification Credit Framework",
    "RHCA": "Red Hat Certified Architect",
    "RHCDS": "Red Hat Certified Datacenter Specialist",
    "RHCSS": "Red Hat Certified Security Specialist",
    "RN": "Registered Nurse",
    "RQF": "Regulated Qualification Framework",
    "RRT": "Registered Respiratory Therapist",
    "SCEA": "Sun Certified Enterprise Architect",
    "SCWCD": "Sun Certified Web Component Developer",
    "SRF": "Self Regulated Framework",
    "SSV": "Senior Standards Verifier",
    "SV": "Standards Verifier",
    "VMD": "Veterinary medical doctor",
    "VT": "Veterinary Technician",
    "A.A.": "Associate of Arts",
    "A.A.-T.": "Associate of Arts for Transfer",
    "A.A.A.": "Associate of Applied Arts",
    "A.A.B.": "Associate of Applied Business",
    "A.A.S.": "Associate of Applied Science",
    "A.A.T.": "Associate of Applied Technology",
    "A.B.": "Bachelor of Arts",
    "A.B.A.": "Associate of Business Administration",
    "A.B.S.": "Associate of Baccalaureate Studies",
    "A.D.N.": "Associate Degree in Nursing",
    "A.E.": "Associate of Electronics",
    "A.E.": "Associate of Engineering",
    "A.E.E.T.": "Associate of Electrical Engineering Technology",
    "A.E.S.": "Associate of Engineering Science",
    "A.E.T.": "Associate of Engineering Technology",
    "A.F.": "Associate of Forestry",
    "A.F.A.": "Associate of Fine Arts",
    "A.G.": "Associate of General Studies",
    "A.I.T.": "Associate of Industrial Technology",
    "A.N.": "Associate of Nursing",
    "A.O.S.": "Associate of Occupational Studies",
    "A.O.T.": "Associate of Occupational Technology",
    "A.P.E.": "Associate of Pre-Engineering",
    "A.P.S.": "Associate of Political Science",
    "A.S.": "Associate of Science",
    "A.S.-C.A.D": "Associate of Science in Computer Assisted Design",
    "A.S.-T.": "Associate of Science for Transfer",
    "A.S.N.": "Associate of Science in Nursing",
    "A.S.P.T.": "Associate in Physical Therapy",
    "A.T.": "Associate of Technology",
    "AAH": "Associate in Allied Health",
    "AAN": "Associate of Arts in Nursing",
    "AARCF": "American Association for Respiratory Care Fellow",
    "AAS": "Associate in Applied Science",
    "AAT": "Associate of Applied Technology",
    "AAT": "Associate of Arts in Teaching",
    "AB": "Bachelor of Arts",
    "ACIArb": "Associate of the Chartered Institute of Arbitrators",
    "ACIB": "Associate of the Chartered Institute of Bankers",
    "ACIBS": "Associate of the Chartered Institute of Bankers in Scotland",
    "ACIBSE": "Associate of the Chartered Institute of Building Services Engineers",
    "ACIM": "Associate Member of the Chartered Institute of Marketing",
    "ACIOB": "Associate of the Chartered Institute of Building",
    "ACP": "Applied Cognitive Psychology",
    "ACRN": "AIDS Certified Registered Nurse",
    "ADN": "Associate's Degree in Nursing"
  }
  